### ISSUE TITLE
Bot doesnt pull new messages

### ISSUE THREAD

**Issue by yesnomaybewtf** [Ondolin/gotify-matrix-bot#10]
Hi, two days ago, the bot stopped sending notifications to my matrix chat.
I did not change anything on my setup.
I noticed that the cache.yaml file was stuck on readMessages: 100
After deleting the file, and restarting the bot, the bot starts do deliver messages again...but only 100, and then stops delivering new messages.

**Comment by Ondolin** [comment]
Ok. This should not happen. Can you please show me your logs? There might be some helpful information in there.

**Comment by yesnomaybewtf** [comment]
Well i guess the logfile doesnt help very much.
`2022/02/18 21:17:00 Currently there are  0 undelivered messages.
2022/02/18 21:17:10 Check for new Messages
2022/02/18 21:17:10 Currently there are  0 undelivered messages.
2022/02/18 21:17:20 Check for new Messages
2022/02/18 21:17:20 Currently there are  0 undelivered messages.
2022/02/18 21:17:30 Check for new Messages
2022/02/18 21:17:30 Currently there are  0 undelivered messages.`
Just tried with a test notification from radarr. Shows up in gotify, but its not delivered by the bot.

**Comment by Ondolin** [comment]
Ok, thanks for sending this. You are right, the problem isn't your setup. There is a bug in the code, and I'll try to fix it as soon as possible.

**Comment by yesnomaybewtf** [comment]
Thanks!

Von meinem iPad gesendet

**Comment by Ondolin** [comment]
I am very sorry that it took so long, but as far as I can say release 2.0.0 should solve your issue. I would really appreciate it if you could try it out yourself.

**Comment by yesnomaybewtf** [comment]
I will try, thank you.

Von meinem iPad gesendet

**Comment by yesnomaybewtf** [comment]
The bot doesnt start (in docker)

Error:
goroutine 1 [running]:                                                                                                                           
github.com/gotify/go-api-client/v2/gotify.NewClient(0x0, 0xc0003f4a50, 0x0)                                                                      
        ***@***.***/gotify/factory.go:11 +0x3b                                                         
gotify_matrix_bot/gotify_messages.init()                                                                                                         
        /app/gotify_messages/messages.go:21 +0x76                                                                                                
panic: runtime error: invalid memory address or nil pointer dereference                                                                          
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x76e6fb]

**Comment by Ondolin** [comment]
I am very sorry that you still have an issue. Since my docker works fine, I have to do a little bit of trial and error.

I have removed the messages.go file in version 2.0.1, since it was in there for historic reasons.

Can you please pull the image and make sure it is the new version (e.g. run `docker pull ondolin/gotify-matrix-bot` and double check the checksum with `sha265:51bac8fd8f5ae41d7fe1a1886c1a3800e3b2a5aa41738a225f274ebd5065a5b4`).

Does this solve your issue?

**Comment by yesnomaybewtf** [comment]
Yes, that solved my issue.
But now i have another one: Error while trying to connect to the webserver:tls: first record does not look like a TLS handshake 

But i think thats because of my crappy matrix setup.

**Comment by Ondolin** [comment]
You can try disabling encryption in the config

**Comment by yesnomaybewtf** [comment]
i did, same error.

**Comment by Ondolin** [comment]
Since I can not reproduce this error I have to believe that you are right and your matrix server configuration is the problem.
  
If you rely want to get into debugging, I would recommend trying it out with the official `matrix.org` homeserver. If it works there, it clearly has to do with your matrix config. 
  
When you find out what the problem is / if I can fix it in this software, please reopen this issue.
